### ISSUE TITLE
Crash after reward video complete

### ISSUE THREAD

**Issue by LordFrz** [unity-plugins/Unity-Admob#88]
I am crashing after most reward videos complete. The interactive ones will not cause a crash, but the ads that you have to watch will cause a crash after they complete. Here is the error from logcat.

```
06-08 11:08:52.030 16342 16342 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.ads.reward.RewardedVideoAdListener.onRewardedVideoCompleted()"
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzahj.onRewardedVideoCompleted(Unknown Source)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzahf.dispatchTransaction(Unknown Source)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzek.onTransact(Unknown Source)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at android.os.Binder.transact(Binder.java:507)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at nx.b(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):20)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.reward.client.l.f(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):27)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):471)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.reward.d.i_(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):88)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.reward.mediation.h.h(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):37)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.reward.client.n.f(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):96)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.a.u(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):471)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.ak.Z(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):261)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.gmsg.am.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):27)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):346)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12685025@12.6.85 (040408-197041431):9)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6688)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
06-08 11:08:52.030 16342 16342 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by unity-plugins** [comment]
Looks like there was an error inside google sdk

**Comment by unity-plugins** [comment]
This is a bug,it was fixed,just wait for one or two day to commit to git

**Comment by unity-plugins** [comment]
Fixed and updated ,enjoy it now.

**Comment by waht123msn** [comment]
After update,it`s also not work````

**Comment by unity-plugins** [comment]
The same error?any error log?

**Comment by waht123msn** [comment]
I have fixed it. I find some old version google lib in it. We must delete all. This is my code:
//	compile(name: 'play-services-ads-lite-11.0.4', ext:'aar')
//	compile(name: 'play-services-basement-11.0.4', ext:'aar')
//	compile(name: 'recyclerview-v7', ext:'aar')
//	compile(name: 'support-compat', ext:'aar')
//	compile(name: 'support-core-ui', ext:'aar')
//	compile(name: 'support-core-utils', ext:'aar')
//	compile(name: 'support-v4-25.3.1', ext:'aar')
//	compile(name: 'support-v4', ext:'aar')

**Comment by keyserjaya** [comment]
> I have fixed it. I find some old version google lib in it. We must delete all. This is my code:
> //	compile(name: 'play-services-ads-lite-11.0.4', ext:'aar')
> //	compile(name: 'play-services-basement-11.0.4', ext:'aar')
> //	compile(name: 'recyclerview-v7', ext:'aar')
> //	compile(name: 'support-compat', ext:'aar')
> //	compile(name: 'support-core-ui', ext:'aar')
> //	compile(name: 'support-core-utils', ext:'aar')
> //	compile(name: 'support-v4-25.3.1', ext:'aar')
> //	compile(name: 'support-v4', ext:'aar')

Hello @waht123msn i have the same issue, and still happend on version 3.16.
Will you tell me the details how to solve it? thank you ^^
